name: phmodeling
channels:
  - conda-forge
dependencies:
  - python=3.10
  - numpy
  - scipy
  - matplotlib
  - tqdm
  - jax
  - pyyaml
  - pip
  - pip:
    - git+https://github.com/deepmind/dm-haiku
    - git+git://github.com/deepmind/optax.git
    - sacred